### PR TITLE
Add missing throws definitions

### LINKED ISSUE #31: Add `throws` definitions for new page methods
Define that `Cloudnode.Error` is thrown by inheritance from `.#sendRequest` in the new page methods such as `.getPage`, `.getNextPage` etc

### PR DESCRIPTION
**Pull request by zefir-git**
Add missing `throws` documentation as described in #31

### CODE REVIEW

**Review by kai-gitt — APPROVED** [review]
It works, although thats a lot of duplicate lines in my opinion

**Comment by zefir-git** [comment]
> It works, although thats a lot of duplicate lines in my opinion

what duplicate lines?

**Comment by kai-gitt** [comment]
> > It works, although thats a lot of duplicate lines in my opinion

> what duplicate lines?

like there's a lot of the same JDoc on everything in README as well as Cloudnode.js [see here](https://github.com/cloudnode-pro/ts-client/pull/32/commits/0405bb83f4ea5ae57059d338bf4f239278437f8d#diff-ca667f4d09dcd9ac9d86d7631deb74437685d219b56f3dee9495f1d83a5267a5R87-R119), all of the throws stuff

**Comment by zefir-git** [comment]
> > > It works, although thats a lot of duplicate lines in my opinion
> 
> > what duplicate lines?
> 
> like there's a lot of the same JDoc on everything in README as well as Cloudnode.js [see here](https://github.com/cloudnode-pro/ts-client/pull/32/commits/0405bb83f4ea5ae57059d338bf4f239278437f8d#diff-ca667f4d09dcd9ac9d86d7631deb74437685d219b56f3dee9495f1d83a5267a5R87-R119), all of the throws stuff

that was the point of this PR. these throws declarations are important and were missing in our documentation. Every method that could throw and error should have a `@throws` to describe that behaviour

**Pull request merged**
